# Generated by Django 3.0.7 on 2021-02-20 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='oring',
            new_name='origin',
        ),
    ]
