# Generated by Django 3.0.7 on 2021-02-21 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_airports_flights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flights',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='origin',
        ),
        migrations.DeleteModel(
            name='Airports',
        ),
        migrations.DeleteModel(
            name='Flights',
        ),
    ]
